apiVersion: apps/v1
kind: Deployment
metadata:
  name: academico-pro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academico-pro-backend
  template:
    metadata:
      labels:
        app: academico-pro-backend
    spec:
      containers:
        - name: academico-pro-backend
          image: academico-pro-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/postgres"
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: academico-pro-backend
spec:
  type: NodePort
  selector:
    app: academico-pro-backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30080 # Porta externa (localhost:30080)
