apiVersion: apps/v1
kind: Deployment
metadata:
  name: academico-pro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academico-pro-frontend
  template:
    metadata:
      labels:
        app: academico-pro-frontend
    spec:
      containers:
        - name: academico-pro-frontend
          image: academico-pro-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: academico-pro-frontend
spec:
  type: LoadBalancer
  selector:
    app: academico-pro-frontend
  ports:
    - port: 80
      targetPort: 3000
